language: java
jdk: oraclejdk8
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: o9VvzE4ih5Rt21yV5PiZBdm7dX7unTbiyQpJVm5HUOEAkHABytVglhEDuCDDAk6wWiIyNdBiwd7jQ2gAOzglFtTWM6ft7Zw+eEIN5CjiDuOpvm4+Xl5q0lFVkTPLnPOyBYoS0u+73SOjCxG3y5lw4AkbTumCM+AnfXzcdclBt6ABF13dZJwcx+bYT4ex6rrAcxFFihWgRcChDDTE7ctptw1rGni5V0ttpBnol151tKF4CeeKgMsCCWN+eMU6UnqWH7XAwJQ1ALmBvLBYTw5TyJwiIewHEDoJ30Gn4+x5eGVaLgbmldqU7GqpC8lYwV4HB1Y2RgXzOpvUE/7+qr3+RnxDFomzFtVhJgsV9ROfCKFxVC80rNRbWIQdI9NAyBVfOJwPD03xpJah2AVwrJM63FpDzEalPHcKIoJqvTKYMzTMmOBEjNID2jh2BGv2n0B85OgNgzPrVhokU8EE83ieoJDoJCrdQy17wYAx+gWR3P1tFgEYIoF+1NOld8qXWKl2465q98kuO9MAZihqE58X39q1CwpbQVmxqZubax5wRGiaHSW7U9JnCMb+E9+rVIsAQtyl/6fQ0szsDGcchuHD+Ma1SeqrN6da8iLizKOwJe7Zm//A+ES1TzTKMLBtADQfldDpwyjljX+h74uLPjh8x1cWbJgAz3nkmoVNxtKbE6I=
  skip_cleanup: true
  before_deploy: "mvn test"
  app: webtech-its
  on:
    branch: master
    repo: FabianHoltkoetter/WebTech-Backend
